152 added new method for cancel booking and confirm
happy-travel/ueda pull request #195
Opened 2021-11-19 13:43 UTC by cyberkarma

152 added new method for cancel booking and confirm

2021-11-19 13:59 UTC, alexander-plekhanov requested changes

2021-11-19 13:59 UTC, alexander-plekhanov commented on src/pages/bookings/booking.js
> +    const cancelManually = () => {
it's a bad practice to have to variables with the same name that differs only in case

2021-11-19 13:59 UTC, alexander-plekhanov commented on src/pages/bookings/booking.js
> +                    <div style={{ display: 'flex', justifyContent: 'space-between', margin: '50px 0 30px' }}>
tabs-only changes

2021-11-19 13:59 UTC, alexander-plekhanov commented on src/components/confirms/confirmation-booking-cancel-manually.js
> +                reason: values.cancelReason,
it's better to call field "reason" because `cancel reason` sounds like a procedure name

2021-11-19 13:59 UTC, alexander-plekhanov commented on src/components/confirms/confirmation-booking-cancel-manually.js
> +
extra empty lines

2021-11-19 13:59 UTC, alexander-plekhanov commented on src/components/confirms/confirmation-booking-cancel-manually.js
> +        return cancel(values);
what's the purpose to return a function's result that is always undefined

2021-11-19 14:01 UTC, cyberkarma commented on src/components/confirms/confirmation-booking-cancel-manually.js
> +
Fixed

2021-11-19 14:03 UTC, cyberkarma commented on src/components/confirms/confirmation-booking-cancel-manually.js
> +                reason: values.cancelReason,
Renamed

2021-11-19 14:07 UTC, cyberkarma commented on src/pages/bookings/booking.js
> +    const cancelManually = () => {
Renamed

2021-11-21 17:30 UTC, kirillta approved these changes

2021-11-22 12:50 UTC, alexander-plekhanov approved these changes

2021-11-22 12:50 UTC, merged